# # version: "3.9"

# # services:
# #   app:
# #     build:
# #       context: .
# #       dockerfile: Dockerfile
# #     ports:
# #       - "8000:8000" # Map application port to host
# #     depends_on:
# #       - db
# #     volumes:
# #       - ./src/main/resources/config.yml:/app/config.yml # Mount configuration file

# #   db:
# #     image: mysql:latest
# #     container_name: db
# #     restart: always
# #     environment:
# #       MYSQL_ROOT_PASSWORD: root
# #       MYSQL_DATABASE: todo_db   
    
# # volumes:
# #   db_data:

# version: "3.9"

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000" # Map application port to host
#     depends_on:
#       - db
#     volumes:
#       - ./src/main/resources/config.yml:/app/config.yml # Mount configuration file
    

#   db:
#     image: mysql:latest
#     container_name: db
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: todo_db
#     ports:
#       - "3306:3306" # Map MySQL port to host
#     # volumes:
#     #   - db_data:/var/lib/mysql # Persist MySQL data
    

# volumes:
#   db_data:

version: '3.8'

services:
  todo-tracker:
    image: todo-tracker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"   # Expose port for Dropwizard application
      - "8081:8081"   # Expose admin port
    depends_on:
      - mysql         # Ensure mysql service is started before the application
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/todo_db?useSSL=false&serverTimezone=UTC
      DATABASE_USER: root
      DATABASE_PASSWORD: root
    volumes:
      - ./src/main/resources/config.yml:/app/config.yml   # Mount config.yml for Dropwizard

  mysql:
    container_name: mysql
    image: mysql:latest   # Use the latest stable version of MySQL
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - "3333:3306"   # Expose MySQL port
    volumes:
      - mysql_data:/var/lib/mysql   # Use a named volume for MySQL persistence

volumes:
  mysql_data:
    driver: local
